server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    finders:
      discovery:
        register-enabled: false # 不向注册中心注册自己
        server-list: 127.0.0.1:9080
    gateway:
      discovery:
        locator:
          enabled: false # 默认为 false。禁用默认的 DiscoveryClient，如果开启，会启用基于服务发现的路由，创建默认的 predicate 和 filter
      routes:
        - id: gateway-provider-service-route # id 要求唯一
          # lb: 表示用 LoadBalancerClient 转发，支持负载均衡
          uri: lb://gateway-provider-service # 转发到服务名为 gateway-provider-service 的目标地址
          predicates: # 断言，用来表示如何匹配 url
            - Path=/gateway-provider/** # 匹配以 /gateway-provider 开头的 uri
          filters: # 过滤器，请求转发前进行额外的操作
            - StripPrefix=1 # 跳过 url 中的第一段
